version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - echo Building, Testing and packaging the application...
      - cd easyRideApp
      - mvn package -DskipTests
  post_build:
    commands:
      - echo Build, Testing and packaging completed.
artifacts:
  files:
    - easyRideApp/target/*.jar
  discard-paths: yes

